# Generated by Django 2.2.1 on 2019-05-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'managed': False},
        ),
    ]
