# Generated by Django 2.2.1 on 2019-05-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_auto_20190521_0526'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='state',
            table='state',
        ),
    ]
