# Generated by Django 2.2.1 on 2019-05-21 17:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0004_urbanarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('statefp', models.CharField(max_length=2)),
                ('countyfp', models.CharField(max_length=3)),
                ('countyns', models.CharField(max_length=8)),
                ('geoid', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('namelsad', models.CharField(max_length=100)),
                ('lsad', models.CharField(max_length=2)),
                ('classfp', models.CharField(max_length=2)),
                ('mtfcc', models.CharField(max_length=5)),
                ('csafp', models.CharField(max_length=3)),
                ('cbsafp', models.CharField(max_length=5)),
                ('metdivfp', models.CharField(max_length=5)),
                ('funcstat', models.CharField(max_length=1)),
                ('aland', models.FloatField()),
                ('awater', models.FloatField()),
                ('intptlat', models.CharField(max_length=11)),
                ('intptlon', models.CharField(max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'county',
                'managed': False,
            },
        ),
    ]
