# Generated by Django 2.1.8 on 2019-05-29 05:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.TextField()),
                ('fulladdress', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zipcode', models.TextField()),
                ('longitude', models.TextField()),
                ('latitude', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('submittime', models.TextField()),
                ('videos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseBasicInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.TextField()),
                ('housetype', models.TextField()),
                ('roomtype', models.TextField()),
                ('bathroom', models.TextField()),
                ('parkinglot', models.TextField()),
                ('washingmachine', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phonenumber', models.TextField()),
                ('email', models.TextField()),
                ('wechat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='images', to='rental.House')),
            ],
        ),
        migrations.CreateModel(
            name='HouseIncluded',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('included', models.TextField()),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='included', related_query_name='included', to='rental.HouseBasicInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HouseLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.TextField()),
                ('latitude', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='HouseNearby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nearby', models.TextField()),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearby', related_query_name='nearby', to='rental.HouseBasicInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HouseOtherRequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otherrequirement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseRentalDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.TextField()),
                ('endtime', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseRequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leaseperiod', models.TextField()),
                ('gender', models.TextField()),
                ('cooking', models.TextField()),
                ('smoking', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='houseotherrequirement',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otherrequirements', related_query_name='otherrequirements', to='rental.HouseRequirement'),
        ),
        migrations.AddField(
            model_name='house',
            name='base',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.HouseBasicInfo'),
        ),
        migrations.AddField(
            model_name='house',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.HouseContact'),
        ),
        migrations.AddField(
            model_name='house',
            name='date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.HouseRentalDate'),
        ),
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.HouseDescription'),
        ),
        migrations.AddField(
            model_name='house',
            name='requirement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.HouseRequirement'),
        ),
    ]
