# Generated by Django 2.2.1 on 2019-06-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='valid',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
