# Generated by Django 2.2.1 on 2019-06-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_house_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.CharField(default='Lease', max_length=20),
        ),
    ]
