# Generated by Django 2.2.1 on 2019-06-12 20:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_house_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMHouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.TextField()),
                ('category', models.CharField(default='Leasing', max_length=20)),
                ('fulladdress', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zipcode', models.TextField()),
                ('longitude', models.TextField()),
                ('latitude', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('submittime', models.TextField()),
                ('starttime', models.TextField()),
                ('endtime', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('phonenumber', models.TextField()),
                ('email', models.TextField()),
                ('wechat', models.TextField()),
                ('price', models.TextField()),
                ('housetype', models.TextField()),
                ('roomtype', models.TextField()),
                ('bathroom', models.TextField()),
                ('parkinglot', models.TextField()),
                ('washingmachine', models.TextField()),
                ('included', models.TextField()),
                ('nearby', models.TextField()),
                ('leaseperiod', models.TextField()),
                ('gender', models.TextField()),
                ('cooking', models.TextField()),
                ('smoking', models.TextField()),
                ('otherrequirements', models.TextField()),
                ('images', models.TextField()),
                ('videos', models.TextField()),
                ('valid', models.CharField(default='1', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
